---
- hosts: hosting
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest
      notify:
        - restart apache
    - name: copy hosting files
      copy:
          src: template/hosting
          dest: /var/www/hosting
          owner: www-data
          group: www-data
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
