---
# - hosts: 34.243.56.110
# - become: yes
# - vars_files:
#     - main.yml
# - tasks:
- name: Install bind9 if needed
  apt:
    name: bind9
    update_cache: yes

- name: Adding conf file for {{domain}} zone
  template:
    src: 'templates/etc/bind/named.conf.local'
    dest: '/etc/bind/named.conf.local'
  notify:
    - restart bind9

- name: Configuring direct zone {{domain}}
  template:
    src: 'templates/var/cache/bind/db.example.com'
    dest: '/var/cache/bind/db.{{domain}}'
  notify:
    - restart bind9

- name: Configuring inverse zone {{domain}}
  template:
    src: 'templates/var/cache/bind/db.10.10.5'
    dest: "/var/cache/bind/db.{{ hostvars['34.243.56.110']['ansible_ssh_host'].split('.')[0] }}.{{ hostvars['34.243.56.110']['ansible_ssh_host'].split('.')[1] }}.{{ hostvars['34.243.56.110']['ansible_ssh_host'].split('.')[2] }}"
  notify:
    - restart bind9
