---
- name: install Mariadb server if needed
  apt:
    name: 'mariadb-server'

- name: Config remote access Mariadb
  copy:
    src: 'templates/etc/mysql/mariadb.conf.d/50-server.cnf'
    dest: '/etc/mysql/mariadb.conf.d/50-server.cnf'
  notify:
    - restart mysql

- name: Install Python mysql library
  apt:
    name: 'python-mysqldb'
