---
- hosts: cloud
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest
      notify:
        - restart apache
    - name: create index.html
      template:
          src: template/index.html
          dest: /var/www/html/index.html
          owner: www-data
          group: www-data
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
