---
- hosts: node1
  become: yes
  vars_files:
    - wordpress_vars.yml
  tasks:
    - name: Install binf9 if needed
      apt:
        name: bind9
        update_cache: yes
    - name: Adding conf file for {{domain}} zone
      template:
        src: file/etc/bind/named.conf.local
        dest: /etc/bind/named.conf.local
    - name: Configuring zone {{domain}}
      template:
        src: file/var/cache/bind/db.example.com
        dest: /var/cache/bind/db.{{domain}}
    - name: Restarting bind9
      service:
        name: bind9
        state: restarted
