---
- hosts: node1
  become: yes
  vars_files:
    - wordpress_vars.yml
  tasks:
    - name: install Mariadb server if needed
      apt:
        name: 'mariadb-server'

    - name: Config remote access Mariadb
      copy:
        src: 'file/etc/mysql/mariadb.conf.d/50-server.cnf'
        dest: '/etc/mysql/mariadb.conf.d/50-server.cnf'
      notify:
        - restart mysql

    - name: Install Python mysql library
      apt:
        name: 'python-mysqldb'

    - name: Create Wordpress database
      mysql_db:
        name: '{{wordpress_db}}'
        state: 'present'

    - name: Copy script sql
      copy:
        src: 'file/wordpress.sql'
        dest: '/tmp/wordpress.sql'

    - name: Creating wordpress tables
      mysql_db:
        name: '{{wordpress_db}}'
        state: 'import'
        target: '/tmp/wordpress.sql'

    - name: Create Wordpress database user
      mysql_user:
        name: '{{wordpress_db_user}}'
        password: '{{wordpress_db_password}}'
        host: '%'
        priv: '{{wordpress_db}}.*:ALL'
        state: 'present'
      notify:
        - restart mysql

    - name: Configuring wordpress site
      shell: mysql -u '{{wordpress_db_user}}' --password='{{wordpress_db_password}}' -D '{{wordpress_db}}' -e "update wp_options set option_value = '{{wordpress_site_title}}' where option_name = 'blogname';"

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
