# - import_playbook: roles/mysql/tasks/main.yaml
# - import_playbook: roles/mysql/tasks/main.yaml
# # - import_playbook: roles/commons.yaml
---
- hosts: node1
  roles:
    - bind9
    - mysql
    - wordpress
