---
- hosts: node2
  become: yes
  tasks:
    - name: install php-fpm if needed
      apt:
        name: php7.0-fpm
      notify:
        - restart php-fpm

    - name: install PhP MySQL library
      apt:
        name: php7.0-mysql

  handlers:
    - name: restart php-fpm
      service:
        name: php7.0-fpm
        state: restarted
